SELECT * FROM marvelstoredb.products;
use marvelstoredb;

-- Category: Marvel Clothes
INSERT INTO products (name, description, price, image_url, category) VALUES 
('Arc Reactor T-Shirt', 'A sleek black cotton tee featuring a glow-in-the-dark Tony Stark Arc Reactor print on the chest. Perfect for geniuses, billionaires, and philanthropists.', 25.00, 'https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1750750070_9215230.jpg?w=1080&dpr=2', 'marvel clothes'),
('Captain America Hoodie', 'A heavy-duty navy blue hoodie with the iconic vibranium shield embroidered on the back. Includes a soft fleece lining for those cold Brooklyn nights.', 45.00, 'https://m.media-amazon.com/images/I/71jRXrE55eL._SX679_.jpg', 'marvel clothes'),
('Spider-Man Tech Shorts', 'Lightweight, breathable red and blue athletic shorts featuring a subtle web-pattern weave. Designed for maximum agility during your daily gym sessions.', 30.00, 'https://m.media-amazon.com/images/I/71a+Jp5xEqL._SX679_.jpg', 'marvel clothes'),
('Black Widow Stealth Jacket', 'A form-fitting black tactical jacket with red hourglass accents. Made from high-durability synthetic leather for a sleek, professional look.', 65.00, 'https://m.media-amazon.com/images/I/81gVlomQjHL._AC_UY1100_.jpg', 'marvel clothes'),
('Thor Worthy Tank Top', 'A grey heather tank top featuring Mjolnir and Norse runes. Great for showing off your gains while training to be the God of Thunder.', 22.00, 'https://m.media-amazon.com/images/I/61Ap6-g++cL._SX679_.jpg', 'marvel clothes'),
('Hulk Smash Sweatpants', 'Extra-roomy purple joggers with a Hulk Smash fist logo on the thigh. Features an elastic waistband that wont rip during a transformation.', 40.00, 'https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1732787875_9257369.jpg', 'marvel clothes'),
('Loki Mischief Windbreaker', 'A green and gold lightweight jacket with a hidden hood. Perfect for unpredictable weather and schemes across the Nine Realms.', 55.00, 'https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1722085121_9500783.jpg?w=1080&dpr=2', 'marvel clothes'),
('Wakanda Forever Polo', 'A sophisticated black polo shirt with subtle tribal patterns on the collar. Made from premium cotton fit for a King of Wakanda.', 35.00, 'https://m.media-amazon.com/images/I/61qyicXsfeL._SY879_.jpg', 'marvel clothes'),
('Iron Man Varsity Jacket', 'A red and gold letterman-style jacket with Stark Industries embroidered on the front. Classic high-school style meets futuristic tech.', 80.00, 'https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1713175160_9310323.jpg?w=480&dpr=2', 'marvel clothes'),
('Groot Nature Tee', 'An eco-friendly tan t-shirt made from organic cotton featuring a I Am Groot graphic. Simple, sustainable, and charming.', 25.00, 'https://images.meesho.com/images/products/837552187/pkdri_512.avif?width=512', 'marvel clothes'),
('Punisher Skull Hoodie', 'A rugged charcoal hoodie featuring the classic white skull logo. Features reinforced stitching for a tough, street-ready aesthetic.', 50.00, 'https://m.media-amazon.com/images/I/A1kl1pPXdaL._AC_UY1000_.jpg', 'marvel clothes'),
('Doctor Strange Cloak Wrap', 'A unique crimson red oversized wrap cardigan with a high collar. Inspired by the Cloak of Levitation, it adds a touch of magic.', 60.00, 'https://m.media-amazon.com/images/I/61AFG5gmfcL._SY879_.jpg', 'marvel clothes'),
('Ant-Man Compression Shirt', 'A red and black moisture-wicking shirt that fits like a second skin. Designed for runners who want to feel fast and small.', 35.00, 'https://www.gymheroics.com/cdn/shop/products/90_d969f7b1-d279-4a64-a040-389a2ac6f8c8_1024x1024.jpg?v=1559108401', 'marvel clothes'),
('Wolverine Flannel', 'A thick, yellow and blue plaid flannel shirt thats tough enough for the Canadian wilderness. Features Logan stitched inside.', 45.00, 'https://i.redd.it/9k0koi6wpbtd1.jpeg', 'marvel clothes'),
('Scarlet Witch Scarlet Robe', 'A comfortable deep red lounging robe with intricate chaos magic symbols. Perfect for staying cozy while rewriting reality.', 70.00, 'https://m.media-amazon.com/images/I/51Jy1U0JdNS._AC_UY1100_.jpg', 'marvel clothes'),
('Deadpool Taco Tee', 'A funny red t-shirt showing Deadpool enjoying a chimichanga. Because even mercenaries need a lunch break and a laugh.', 25.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ3el1wTlX-1ZttCzdwQlx24gvNxAuVPlW4nbStg5Ak_Psxgg7_6TpCZzKZHgsWl0mrFIm-WOZyXIJpXJeQyqMEAlYfG2zEgA', 'marvel clothes'),
('Thanos Infinity Cap', 'A gold-colored snapback hat featuring six colorful gems on the side. A powerful accessory for those who want to balance their outfit.', 28.00, 'https://m.media-amazon.com/images/I/61qLeyPFltL._AC_SX679_.jpg', 'marvel clothes'),
('Hawkeye Archer Vest', 'A purple and black utility vest with multiple pockets for all your daily arrows and gadgets. Lightweight and practical.', 50.00, 'https://www.marveljacket.com/wp-content/uploads/2020/12/Hawkeye-The-Avengers-Vest.jpg', 'marvel clothes'),
('Ms. Marvel Jersey', 'A bright blue and red jersey with a large gold lightning bolt. Stylish, stretchy, and perfect for the hero in training.', 40.00, 'https://i.ebayimg.com/images/g/tjsAAOSw6s9i17DR/s-l1200.jpg', 'marvel clothes'),
('Winter Soldier Arm Sleeve', 'A silver-colored compression sleeve designed to mimic Buckys bionic arm. Provides muscle support and a legendary look.', 20.00, 'https://i.etsystatic.com/13375858/r/il/ba344b/6838982341/il_1588xN.6838982341_mltf.jpg', 'marvel clothes');