SELECT * FROM marvelstoredb.products;
use marvelstoredb;

-- Category: Marvel Action Figures
INSERT INTO products (name, description, price, image_url, category) VALUES 
('Iron Man MK 85', 'A highly detailed 6-inch figure with 20 points of articulation and interchangeable hands.', 25.00, 'https://m.media-amazon.com/images/I/51xpaYuV3fL._SL1000_.jpg', 'marvel action figures'),
('Cap Endgame Edition', 'Captain America featuring his scaled armor and a broken shield accessory.', 28.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRuTecpD8UfaFC0tZrhQfoIk6FBj_qapYzoY2atBgnJM1P8fRnXfhcbd0QNIMQy9FuhoEv2OvzpzL8Dnqcl3ddm6Ji8BreBIVdf3clMfxN8pAPsf1mZwdNW', 'marvel action figures'),
('Thanos Deluxe', 'An oversized 9-inch Thanos figure with a removable Infinity Gauntlet.', 40.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTeq5RIf-mvU91npVfbSToTYiAbYyMTpFERkdcJAwoNoa7lwEtNJwWuyGF-RxQDaLOAY_H5DOw5ktANmSUnUiW9165BbQiEIdufVboa7lsPCM5tjGsBkxydtw', 'marvel action figures'),
('Spider-Man Integrated', 'Based on No Way Home, this figure features the black and gold suit.', 25.00, 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQw7U5gWqDVW8ReZBl9-OT-RPNfWENQy19kyd4NgFTQbIPot4GwXY_sz6Nu0jxUcl8IKE8TA4ZZWgT525640bIATOQy-j72yw', 'marvel action figures'),
('Thor Love and Thunder', 'Thor in his vibrant blue and gold armor with a glowing Stormbreaker accessory.', 27.00, 'https://m.media-amazon.com/images/I/61+HoXk0BvL._AC_UF894,1000_QL80_.jpg', 'marvel action figures'),
('Black Panther Shuri', 'The new Black Panther figure with vibranium-glow purple accents.', 25.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRDsiqjZa0ecGE1bn2IAP5TN68njBSbzOB9f3Xygt5-l_hdMdGv9FOxpGGI0g4Otw6X8NZI0DQ9ZZpn1Q14l7LxqJngKluCI-2WSW9ilPMYhHghsMZpgd0Cjw', 'marvel action figures'),
('Hulk Gladiator', 'Hulk in his Thor: Ragnarok arena armor, complete with a massive hammer.', 35.00, 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRqDQuN-PELKiF79bQdgeibQEEgenkkKWp3eapxqoyQaOZtKTkuZdHMYD8byxxoZdR_qX309y0nOvJvMoENbjMQpu9xESCoXO6rVxfm9jGzNI96bS7UPM9PT38', 'marvel action figures'),
('Scarlet Witch Multiverse', 'Wanda in her full Scarlet Witch regalia with translucent red chaos magic hands.', 30.00, 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTAOnKlx14s0g07bcEOAsLdoq_K3HUHsBNVto8jn2E044zMaeLUuNwjxAaG4nxl474GDqhlPrywadQEqEYYZShurybBGVsQIyiLy975Djn2EL1QnOm-UxaJ', 'marvel action figures'),
('Doctor Strange Defender', 'A special edition figure of Defender Strange with an alternate Portal backdrop.', 26.00, 'https://shop.robotrobot.com/cdn/shop/products/65e49208a3dab6899d0a36165fef9624.jpg?v=1676022437&width=1946', 'marvel action figures'),
('Loki TVA Suit', 'Loki in his Variant jacket, accompanied by a small Alligator Loki figure.', 24.00, 'https://houseofcollectibles.com.tr/wp-content/uploads/2024/03/hot-toys-loki-tva-suit-sixth-scale-figure-ht1-543-s0-p5-5000x5000-i29556.jpg', 'marvel action figures'),
('Moon Knight', 'A stunning white-wrapped Moon Knight figure with crescent dart accessories.', 30.00, 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQjIktWbA71Rw5q5Jb1-Hno0j5MXxOv2MsMksPvvowRTZT4JYdCcA6GuOadG5FaR_YVOsFcCDjhShOAZ9rd6N5dqlIrmWO9i77w8Oaj2l8sTaBwNhgtTwRAVQ', 'marvel action figures'),
('Green Goblin Retro', 'The classic Willem Dafoe Goblin with a removable mask and a poseable glider.', 32.00, 'https://m.media-amazon.com/images/I/71UQM05uxoL._AC_UF1000,1000_QL80_.jpg', 'marvel action figures'),
('Venom Movie', 'A bulky, detailed Venom figure with tendril attachments.', 35.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQqvOMbduf8MfaBg8evDkW_qQFlMSrbSdOLaWlov-9J8_QViwK6mYVZJ4WL9i6MxMljxY0P17jEAa6v2iaiIEKEljbNGpnDy_nTscRNXo6C8ZeHhs2hry92Sbg', 'marvel action figures'),
('Star-Lord Vol 3', 'Peter Quill in the new blue Guardians uniform with dual blasters.', 25.00, 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ8smOu-pexhxzOZGX1mqSXrSvbKtyQKizam4W-vjTD1J8sMyZAoKzAQN7BGif1FiIMePUCS0n1eg8eaTGuW08UvBRkZVnJRddNzhtsrcMnX2jMDcoiYt-dnQ', 'marvel action figures'),
('Groot Adult', 'A towering Groot figure with vine-extension arms and a small Rocket Raccoon.', 28.00, 'https://m.media-amazon.com/images/I/61hegvNPZQL.jpg', 'marvel action figures'),
('Captain Marvel Binary', 'Carol Danvers in her powered-up Binary mode with energy bursts.', 26.00, 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSO9SPfqDnTGE8Yuu40RsiEh1dFoDVzABB84fb1fjs8lqYX0poGyXE1NPKfwyd1PVPuc8e-10L11B2uTQ8g_lGSi6mSLJbGmLWujDek7QoHZz2qQNdzfBYF1Q', 'marvel action figures'),
('Winter Soldier Classic', 'Bucky Barnes in his tactical gear with a sniper rifle and chrome-painted arm.', 25.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcThyzEgk5ieVfp-CKUGIvt0qF5k8ZFidMu1E1ML8hDY6RYOdux3XCzvct5dWy9X3ms3kt77AAmIrlBquG5Yu69AVTKzgIVOrqJaPc9pYYxRbZhPP57bK16UzA', 'marvel action figures'),
('Shang-Chi', 'The Master of Kung Fu with ten glowing rings that can be attached.', 24.00, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRtzBox9vthwaIAN6LSI5ZAnvuaP-8kO_V943LQm-VmRlQdB9HeNZ5PumAbNHthpk2dfBlBn_qX4pLmAb0w9Elx0PEjiwXa_p5E9SZMuTZgg5789WnQ0VY8', 'marvel action figures'),
('Daredevil Yellow Suit', 'A classic tribute figure featuring Matt Murdock in his original yellow and red suit.', 22.00, 'https://popcollectibles.store/cdn/shop/products/DSC00116_1024x1024.jpg?v=1677007796', 'marvel action figures'),
('The Watcher BAF', 'A massive, cosmic figure of Uatu the Watcher. Stands head and shoulders above the rest.', 50.00, 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTLkoJg1hujWMI6vjWHwtl0EeB8a2XtzYGzywjFeG5AvbvPWHfr3Dx-eUp5VyuyvffoPvK7tRSCsjLlmrpVTZyitZYInBTb1w', 'marvel action figures');