SELECT * FROM marvelstoredb.products;
use marvelstoredb;

-- Category: Marvel Magnets
INSERT INTO products (name, description, price, image_url, category) VALUES 
('Avengers A Magnet', 'The classic brushed-metal Avengers logo for your fridge. A symbol of unity for the mightiest heroes in your kitchen.', 8.00, 'https://m.media-amazon.com/images/I/61cKZCK+IiL._SL1500_.jpg', 'marvel magnets'),
('Iron Man Helmet 3D', 'A miniature 3D molded Iron Man mask with reflective gold eyes. Strong enough to hold up your heaviest grocery lists.', 12.00, 'https://makerworld.bblmw.com/makerworld/model/USb61ddc5cdcef79/design/2024-03-10_ce5ee93287faf.jpg?x-oss-process=image/resize,w_1000/format,webp', 'marvel magnets'),
('Spider-Man Face', 'A vibrant red and white rubberized magnet of Peter Parkers mask. Sticks to surfaces as easily as Spidey sticks to walls.', 9.00, 'https://m.media-amazon.com/images/I/51UN944pLQL.jpg', 'marvel magnets'),
('Mjolnir Hammer Magnet', 'A heavy-duty pewter magnet shaped like Thors hammer. Only the worthy can move it from the freezer door.', 15.00, 'https://cdn.thingiverse.com/assets/98/60/0c/fe/ae/large_display_IMG_3264.jpg', 'marvel magnets'),
('Captain America Shield', 'A circular, red, white, and blue enamel magnet. Built to protect your fridge from boring decorations.', 10.00, 'https://media.printables.com/media/prints/7399/images/54977_8a883190-cf3a-4946-957b-609b0e43a48e/thumbs/inside/1280x960/jpg/20190618_200820_7399.webp', 'marvel magnets'),
('Hulk Fist Smash', 'A green, textured magnet that looks like the Hulk is punching through your refrigerator door.', 12.00, 'https://makerworld.bblmw.com/makerworld/model/US42bb16975ca3c8/design/2024-08-02_93c0e6970e29b.png?x-oss-process=image/resize,w_1000/format,webp', 'marvel magnets'),
('Black Panther Mask', 'A sleek black magnet with silver highlights representing the King of Wakanda. Elegant and powerful.', 11.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs40KO3lpIWxY0Vo7wOZ0wf0ogd_z8coUF6g&s', 'marvel magnets'),
('Deadpool Speech Bubble', 'A magnet shaped like a comic book speech bubble featuring a sassy Deadpool quote.', 9.00, 'https://m.media-amazon.com/images/I/61QKViw4kZL._AC_UF894,1000_QL80_.jpg', 'marvel magnets'),
('Groot Flower Pot', 'A cute, small magnet of Baby Groot in a pot. Guaranteed to make you smile every time you go for a snack.', 10.00, 'https://i.etsystatic.com/14344778/r/il/c5491d/2386366618/il_340x270.2386366618_nrz0.jpg', 'marvel magnets'),
('Infinity Gauntlet', 'A golden magnet featuring all six Infinity Stones. Control the destiny of your kitchen with a single snap.', 18.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM5qjosDtIGZg4kvobspws5pmGAuxUke61yA&s', 'marvel magnets'),
('SHIELD Emblem', 'A formal silver and black eagle logo of the worlds premier spy organization. Classified information not included.', 10.00, 'https://i5.walmartimages.com/seo/Marvel-Agents-of-S-H-I-E-L-D-Insignia-2-5-x-3-5-Inch-Magnet_dccf87b2-0ba4-4f3e-86b0-b65bba6ca982.0f496824c7b7a9e30797c6c170005329.jpeg?odnHeight=208&odnWidth=208&odnBg=FFFFFF', 'marvel magnets'),
('Loki Helmet Magnet', 'A golden magnet featuring Lokis iconic long-horned helmet. Adds a touch of mischief to your home decor.', 13.00, 'https://img-new.cgtrader.com/items/6705640/09f6d944f5/loki-fridge-magnet-stl-3d-printable-trickster-god-magnet-3d-model-09f6d944f5.webp', 'marvel magnets'),
('Venom Teeth', 'A terrifyingly cool magnet of Venoms open jaw and long tongue. Not for the faint of heart.', 12.00, 'https://fbi.cults3d.com/uploaders/26944097/illustration-file/d66cb522-55ad-4e40-875b-dc2b55d88e7a/VENOM.png', 'marvel magnets'),
('Guardians Cassette Tape', 'A retro Awesome Mix Vol. 1 tape magnet. A nostalgic tribute to Star-Lord.', 9.00, 'https://i.etsystatic.com/22277810/r/il/e3d2ca/5717363391/il_fullxfull.5717363391_1w1z.jpg', 'marvel magnets'),
('Daredevil Horns', 'A simple, deep red magnet shaped like the Devil of Hells Kitchen. Fearless design for a bold kitchen.', 9.00, 'https://www.toynk.com/cdn/shop/files/SOI-DDVLMASK3DPIN1-C-2_1800x.jpg?v=1754681054', 'marvel magnets'),
('Punisher Skull', 'A flat, matte black skull magnet for those who prefer a grittier look for their appliances.', 8.00, 'https://i.ebayimg.com/00/s/MTU2OFgxNjAw/z/8qkAAOSwXUJjxhp6/$_12.JPG?set_id=880000500F', 'marvel magnets'),
('X-Men X Logo', 'A classic yellow and black X magnet. Celebrate mutant pride and Charles Xaviers school.', 10.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOlEXC_pG1lPW0yWMC2DouhBBHzNZHXQUo_w&s', 'marvel magnets'),
('Ant-Man Helmet', 'A detailed silver and red magnet that looks just like Scott Langs shrinking tech.', 11.00, 'https://i.ebayimg.com/images/g/VEQAAOSw5UVa2J8P/s-l1200.jpg', 'marvel magnets'),
('Doctor Strange Eye', 'A magnet shaped like the Eye of Agamotto. It might not control time, but it looks mystical.', 14.00, 'https://media.dcbservice.com/xlarge/OCT172814.jpg', 'marvel magnets'),
('Wolverine Claws', 'Three metallic-looking claw marks that stick to your fridge. Shows everyone that a mutant was here.', 11.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn0x1EEPZ06RCHxS5hM8oSHZ1HzL7q9Kw0gw&s', 'marvel magnets');